version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: livio_rodrigues/php
    container_name: app
    restart: unless-stopped
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s php-fpm
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db
      - redis
      #db:
      #  condition: service_healthy

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - app-network

    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network


  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    #command: --innodb-use-native-aio=0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

    environment:
      MYSQL_DATABASE: ms_devops
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    #healthcheck:
    #  test: ["CMD-SHELL",'mysql -uroot --database=ms_devops --password=root  --execute="select count(table_name)>0 from information_schema.tables;" --skip-column-names -B']
    #  interval: 10s
    #  timeout: 10s
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
